version: '3.1'
services:
  db:
    image: mysql
    container_name: devdojo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - devdojo_mysql_data:/var/lib/mysql

volumes:
  devdojo_mysql_data: